# Read about configuration here: https://jekyllrb.com/docs/configuration/options/
title: State of Eth
description: A dashboard to monitor the state of Ethereum and to promote positive change.
keywords: ethereum, decentralization, health, diversity, eth
url: https://stateofeth.com
permalink: pretty # Do not change this, it will break all links
timezone: America/New_York
markdown: kramdown
livereload: true
port: 4400
environment: production

# Plugins
plugins:
  - jekyll_include_plugin # https://github.com/flant/jekyll_include_plugin
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from
redirect_from: # jekyll-redirect-from
  json: false

# Global variables


# Toast
enable_toast: false
toast_msg_id: 1 # must increment when creating a new message
toast_title: Ether Alpha's Gitcoin grant is live!
toast_msg: This round runs through August 29th. If you enjoy this or <a href='https://etheralpha.org/' target='_blank'>other tools</a> created, please support to help maintain existing projects and fund new ones." # Best when under 100 characters
toast_link: https://stateofeth.com # Optional, leave blank to omit
toast_link_text: Donate
# August 29, 23:59:59 GMT+0
toast_expiration: 30000000000 # epoch time in seconds
